---
deployment:
  tasks:
    - export DEPLOYPATH=/home/julehxnr/public_html/
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r images $DEPLOYPATH
    - /bin/cp -r documents $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp cv.html $DEPLOYPATH
    - /bin/cp courses-graduate.html $DEPLOYPATH